"""
TITAN Engine v6.0 - E-Agent (Evaluator / RAGEvaluator)
Reads the code generated by D-Agent, statically analyzes it, and provides 'Feedback'.
If it passes, it returns True. If it fails, it returns False + Feedback text for D-Agent to evolve.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from core_generators.llm_client import LLMClient
from logger import get_logger

log = get_logger("titan_e_agent")

SITE_DIR = os.path.join(os.path.dirname(__file__), "shipmicro_site")

class EAgent:
    def __init__(self):
        self.llm = LLMClient()
    
    def evaluate(self, app_id: str, proposal: dict) -> tuple[bool, str]:
        """Returns (Passed, Feedback_String)"""
        log.info(f"⚖️ TITAN E-Agent: Starting Evaluation for [{app_id}]")
        
        api_path = os.path.join(SITE_DIR, "src", "app", "api", app_id, "route.ts")
        page_path = os.path.join(SITE_DIR, "src", "app", "tools", app_id, "page.tsx")
        
        if not os.path.exists(api_path) or not os.path.exists(page_path):
            error = f"Missing generated files. API: {os.path.exists(api_path)}, Page: {os.path.exists(page_path)}"
            log.warning(f"❌ E-Agent Fail: {error}")
            return False, error
            
        with open(api_path, "r", encoding="utf-8") as f:
            api_code = f.read()
            
        with open(page_path, "r", encoding="utf-8") as f:
            page_code = f.read()
            
        # LLM STATIC ANALYSIS for 'Micro-SaaS Viral Web App' rules
        prompt = f"""You are the strict "E-Agent" (Evaluator) of the TITAN Engine.
Your job is to evaluate if the D-Agent (Developer) correctly implemented the viral web app proposal.

Proposal:
{proposal}

--- API CODE (route.ts) ---
```typescript
{api_code}
```

--- UI COMPONENT (page.tsx) ---
```tsx
{page_code}
```

EVALUATION CHECKLIST:
1. Is the page a `"use client";` component?
2. Does it properly collect inputs and call `/api/{app_id}` via POST?
3. Does it have the "typewriter effect" (revealing result character by character)?
4. Does it successfully interrupt the typewriter effect with a "9.9元" Paywall popup precisely related to the `paywall_trigger`?
5. Does `handlePay` clear the paywall and resume the typing effect?
6. Does the UI look like a dark, premium Tailwind application?
7. Is there a clear `export default function...` without any generic syntax errors?

DECISION:
If EVERYTHING is perfect, reply EXACTLY with just the word: "PASSED"
If ANYTHING is wrong, missing, or buggy, reply with: "FAILED:" followed by a specific, actionable instruction to fix it (this feedback will be sent back to D-Agent for evolution).

DO NOT output markdown, just plain text starting with PASSED or FAILED:
"""
        log.info(f"   🤖 E-Agent: Asking LLM to cross-examine code...")
        response = self.llm.generate(prompt, system_prompt="You are a ruthless Senior Staff Engineer code reviewer.")
        
        response = response.strip()
        if response.startswith("PASSED"):
            log.info(f"✅ E-Agent: Code PASSED evaluation!")
            return True, "PASSED"
        else:
            reason = response.replace("FAILED:", "").strip()
            log.warning(f"❌ E-Agent: Code FAILED. Reason: {reason}")
            return False, reason

if __name__ == "__main__":
    if len(sys.argv) > 1:
        app_id_test = sys.argv[1]
        agent = EAgent()
        # Mock evaluation run
        passed, fb = agent.evaluate(app_id_test, {"name": "Test Mock"})
        print(f"Passed: {passed}\nFeedback: {fb}")
    else:
        print("Usage: python titan_e_agent.py <app_id>")
